project 'CustomFont2.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '10.2'
#platform :ios, '9.0'

target 'CustomFont2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'SnapKit', '~> 3.2.0'
   pod 'SnapKit'
  # Pods for CustomFont

end
